src/Entity/HotelServicio.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * HotelServicio
 *
 * @ORM\Table(name="hotel_servicio")
 * @ORM\Entity(repositoryClass="App\Repository\HotelServicioRepository")
 */
class HotelServicio
{
   /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="anotacion", type="string", length=200, nullable=true)
     */
    private $anotacion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Hotel", inversedBy="hotelServicios")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_hotel;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Servicio", inversedBy="hotelServicios")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_servicio;

    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getAnotacion(): ?string
    {
        return $this->anotacion;
    }

    public function setAnotacion(?string $anotacion): self
    {
        $this->anotacion = $anotacion;

        return $this;
    }

    public function getIdHotel(): ?Hotel
    {
        return $this->id_hotel;
    }

    public function setIdHotel(?Hotel $id_hotel): self
    {
        $this->id_hotel = $id_hotel;

        return $this;
    }

    public function getIdServicio(): ?Servicio
    {
        return $this->id_servicio;
    }

    public function setIdServicio(?Servicio $id_servicio): self
    {
        $this->id_servicio = $id_servicio;

        return $this;
    }
}

src/Controller/DetalleHotelController.php
<?php

namespace App\Controller;

use App\Entity\Hotel;
use App\Entity\Estancia;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DetalleHotelController extends AbstractController
{
    /**
     * @Route("/detalleHotel/{hotel}/{estancia?null}", name="detalleHotel")
     */
    public function index(Hotel $hotel,Estancia $estancia=null)
    {        
        if (!$hotel->getEstancias()->contains($estancia)){
            $estancia = null;
        }

        return $this->render('detalle_hotel/index.html.twig', [
            'hotel' => $hotel,
            'estancia' => $estancia
        ]);        
    }
}

templates/detalle_hotel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DetalleHotelController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container mt-2">

    
   


    <div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/images/Hoteles/{{hotel.imagenPortada}}" class="d-block w-100" alt="...">
    </div>

    {% for imagen  in hotel.imagenesHotels %}
      <div class="carousel-item">
        <img src="/images/Hoteles/{{imagen.url}}" class="d-block w-100" alt="...">
      </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
    </div>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h3 class="card-title">{{hotel.nombre}}</h3>
        {% if estancia != null %}
        <h4 class="card-text">Oferta</h4>
        <p></p>
                <ul>
                    <li>Habitación: {{estancia.habitacion}}</li>
                    <li>Número de noches: {{estancia.noches}}</li>
                    <li>Pensión: {{estancia.tipoPension}}</li>
                </ul>
         {% endif %}       
      </div>
    </div>
  </div>
</div>

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Descripción del hotel
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
       <p>{{hotel.descripcion}}</p>
      </div>
    </div>
  </div>
 
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Servicios
        </button>
      </h2>
  </div>
  
  
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        <ul>
         {% for hotelServicio in hotel.hotelServicios %}
            <li>{{hotelServicio.idServicio.nombre}}</li>
          {% else %}
            <li> No hay servicios </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Ubicación y contacto
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
       <ul style="list-style-type: none;">
            <li><b>Dirección:</b> {{hotel.direccion}}</li>
            <li><b>Ciudad:</b> {{hotel.ciudad}}</li>
            <li><b>Provincia:</b> {{hotel.provincia}}</li>
            <li><b>Sitio Web:</b> <a href={{hotel.web}} target="_blank"> {{hotel.web}}</a></li>
            <li><b>Email:</b> {{hotel.email}}</li>
            <li><b>Teléfono:</b> {{hotel.telefono}}</li>
        </ul>
      </div>
    </div>
  </div>
</div>






</div>

{% endblock %}