src/Entity/Estancia.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Estancia
 *
 * @ORM\Table(name="estancia")
 * @ORM\Entity(repositoryClass="App\Repository\EstanciaRepository")
 */
class Estancia
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var int|null
     *
     * @ORM\Column(name="noches", type="integer", nullable=true)
     */
    private $noches;

    /**
     * @var int|null
     *
     * @ORM\Column(name="personas", type="integer", nullable=true)
     */
    private $personas;

    /**
     * @var string|null
     *
     * @ORM\Column(name="habitacion", type="string", length=150, nullable=true)
     */
    private $habitacion;

    /**
     * @var string|null
     *
     * @ORM\Column(name="tipo_pension", type="string", length=500, nullable=true)
     */
    private $tipoPension;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EstanciaPack", mappedBy="id_estancia")
     */
    private $estanciaPacks;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Hotel", inversedBy="estancias")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_hotel;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LineaPedido", mappedBy="id_estancia")
     */
    private $lineaPedidos;

    public function __construct()
    {
        $this->pedidos = new ArrayCollection();
        $this->estanciaPacks = new ArrayCollection();
        $this->lineaPedidos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    

    public function getNoches(): ?int
    {
        return $this->noches;
    }

    public function setNoches(?int $noches): self
    {
        $this->noches = $noches;

        return $this;
    }

    public function getPersonas(): ?int
    {
        return $this->personas;
    }

    public function setPersonas(?int $personas): self
    {
        $this->personas = $personas;

        return $this;
    }

    public function getHabitacion(): ?string
    {
        return $this->habitacion;
    }

    public function setHabitacion(?string $habitacion): self
    {
        $this->habitacion = $habitacion;

        return $this;
    }

    public function getTipoPension(): ?string
    {
        return $this->tipoPension;
    }

    public function setTipoPension(?string $tipoPension): self
    {
        $this->tipoPension = $tipoPension;

        return $this;
    }

   

    /**
     * @return Collection|EstanciaPack[]
     */
    public function getEstanciaPacks(): Collection
    {
        return $this->estanciaPacks;
    }

    public function addEstanciaPack(EstanciaPack $estanciaPack): self
    {
        if (!$this->estanciaPacks->contains($estanciaPack)) {
            $this->estanciaPacks[] = $estanciaPack;
            $estanciaPack->setIdEstancia($this);
        }

        return $this;
    }

    public function removeEstanciaPack(EstanciaPack $estanciaPack): self
    {
        if ($this->estanciaPacks->contains($estanciaPack)) {
            $this->estanciaPacks->removeElement($estanciaPack);
            // set the owning side to null (unless already changed)
            if ($estanciaPack->getIdEstancia() === $this) {
                $estanciaPack->setIdEstancia(null);
            }
        }

        return $this;
    }

    public function getIdHotel(): ?Hotel
    {
        return $this->id_hotel;
    }

    public function setIdHotel(?Hotel $id_hotel): self
    {
        $this->id_hotel = $id_hotel;

        return $this;
    }

    /**
     * @return Collection|LineaPedido[]
     */
    public function getLineaPedidos(): Collection
    {
        return $this->lineaPedidos;
    }

    public function addLineaPedido(LineaPedido $lineaPedido): self
    {
        if (!$this->lineaPedidos->contains($lineaPedido)) {
            $this->lineaPedidos[] = $lineaPedido;
            $lineaPedido->setIdEstancia($this);
        }

        return $this;
    }

    public function removeLineaPedido(LineaPedido $lineaPedido): self
    {
        if ($this->lineaPedidos->contains($lineaPedido)) {
            $this->lineaPedidos->removeElement($lineaPedido);
            // set the owning side to null (unless already changed)
            if ($lineaPedido->getIdEstancia() === $this) {
                $lineaPedido->setIdEstancia(null);
            }
        }

        return $this;
    }
}

src/Entity/LineaPedido.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LineaPedidoRepository")
 */
class LineaPedido
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\Column(type="float")
     */
    private $precio;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_fin;

    /**
     * @ORM\Column(type="boolean")
     */
    private $usado;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pedido", inversedBy="lineaPedidos", cascade={"persist"})
     */
    private $id_pedido;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pack", inversedBy="lineaPedidos" , cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_pack;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Estancia", inversedBy="lineaPedidos")
     */
    private $id_estancia;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getPrecio(): ?float
    {
        return $this->precio;
    }

    public function setPrecio(float $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getFechaFin(): ?\DateTimeInterface
    {
        return $this->fecha_fin;
    }

    public function setFechaFin(\DateTimeInterface $fecha_fin): self
    {
        $this->fecha_fin = $fecha_fin;

        return $this;
    }

    public function getUsado(): ?bool
    {
        return $this->usado;
    }

    public function setUsado(bool $usado): self
    {
        $this->usado = $usado;

        return $this;
    }

    public function getIdPedido(): ?Pedido
    {
        return $this->id_pedido;
    }

    public function setIdPedido(?Pedido $id_pedido): self
    {
        $this->id_pedido = $id_pedido;

        return $this;
    }

    public function getIdPack(): ?Pack
    {
        return $this->id_pack;
    }

    public function setIdPack(?Pack $id_pack): self
    {
        $this->id_pack = $id_pack;

        return $this;
    }

    public function getIdEstancia(): ?Estancia
    {
        return $this->id_estancia;
    }

    public function setIdEstancia(?Estancia $id_estancia): self
    {
        $this->id_estancia = $id_estancia;

        return $this;
    }
}

src/Entity/PackAleatorio.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PackAleatorioRepository")
 */
class PackAleatorio
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="float")
     */
    private $Precio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titulo;

    /**
     * @ORM\Column(type="float")
     */
    private $maximo;

    /**
     * @ORM\Column(type="float")
     */
    private $minimo;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $imagenPortada;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrecio(): ?float
    {
        return $this->Precio;
    }

    public function setPrecio(float $Precio): self
    {
        $this->Precio = $Precio;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->Titulo;
    }

    public function setTitulo(string $Titulo): self
    {
        $this->Titulo = $Titulo;

        return $this;
    }

    public function getMaximo(): ?float
    {
        return $this->maximo;
    }

    public function setMaximo(float $maximo): self
    {
        $this->maximo = $maximo;

        return $this;
    }

    public function getMinimo(): ?float
    {
        return $this->minimo;
    }

    public function setMinimo(float $minimo): self
    {
        $this->minimo = $minimo;

        return $this;
    }

    public function getImagenPortada(): ?string
    {
        return $this->imagenPortada;
    }

    public function setImagenPortada(string $imagenPortada): self
    {
        $this->imagenPortada = $imagenPortada;

        return $this;
    }
}

src/Controller/PaquetesController.php
<?php

namespace App\Controller;

use App\Entity\Grupo;
use App\Entity\Pack;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PaquetesController extends AbstractController
{
    /**
     * @Route("/paquetes", name="paquetes")
     */
    public function index()
    {
        return $this->render('paquetes/paquetesGrupo.html.twig', [
            'controller_name' => 'PaquetesController',
        ]);
    }

    /**
     * @Route("/paquetes/{grupo}", name="paquetesGrupo")
     */
    public function paquetesGrupo(Grupo $grupo)
    {   

        return $this->render('paquetes/paquetesGrupo.html.twig',[
            'grupo'=> $grupo
        ]
        );
    }

    /**
     * @Route("/paquetes/{grupo}/{paquete}", name="infoPaquete")
     */
    public function infoPaquete(Grupo $grupo, Pack $paquete)
    {
        if ($grupo->getPacks()->contains($paquete)){
            return $this->render('paquetes/index.html.twig',[
                'paquete' => $paquete,
                'grupo' => $grupo
            ]); 
        }
        
        else {
            return $this->redirect($this->generateUrl('index'));
        }
        
    }
}

templates/paquetes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TripAddict | Paquete{% endblock %}

{% block body %}
  <div class="d-flex justify-content-between">

    <div class="card col-8 align-items-start mb-3 p-2">
      <div class="row no-gutters">

        <div class="col-md-4">
          <img src="\images\ImagenesPortadas\{{paquete.imagenPortada}}" class="card-img cuadradoGrande" id="destino" alt="...">
        </div>

        <div class="col-md-8">
          <div class="card-body">
            <h3 class="card-title">{{paquete.nombre}}</h3>
            <h5 class="card-title">Grupo: {{grupo.titulo}}</h5>
            <p class="card-text">{{paquete.descripcion}}</p>
          </div>
        </div>

        <img src="\images\ImagenesPortadas\{{paquete.imagenPortada}}" class="float-left cuadrado m-2" alt="..." style="width:50px" id="imagen1" onclick='copiar(this)'>

        <img src="\images\mapapackdesayuno.jpg" class="float-left cuadrado m-2" alt="..." style="width:50px" id="imagen1" onclick='copiar(this)'>
      </div>
    </div>


  {% if paquete.estanciaPacks|length > 0 %}
  <div class="card col-3   align-items-stretch align-self-start ">
    <div class="card-body text-right">
      <form name="formularioCompra" action='/carrito/add' method='POST'>
      <p class="validity">
        Validez: 06 Septiembre 2021 </p>
      <label for="cantidad">Cantidad</label>
      <select class='form-control'  id="cantidad" name="cantidad" tittle="Cantidad">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
      </select>
      <input name='idPack' type='hidden' value='{{paquete.id}}'/>

      <h2> {{paquete.precio}}€</h3>
        <p class="text-center">
          <strong> <i class="fa fa-envelope-o" aria-hidden="true"></i> e-cofre enviado por e-mail</strong>
          Inmediatamente
          <button type="submit" class="mt-3 btn btn-block btn-primary">Comprar</button></p>
      </form>
    </div>
  </div>
  {% endif %}
</div>

<div class="card">
  <h2 class="card-header">Estancias</h2>
  <div class="card-body">
    <div class='row'>
      {% for estanciaPack in paquete.estanciaPacks %}
      <div class='col-md-5'>
        <div class="card">
          <a href="/detalleHotel/{{estanciaPack.idEstancia.idHotel.id}}/{{estanciaPack.idEstancia.id}}"
            style="text-decoration:none;">
            <img src="/images/Hoteles/{{estanciaPack.idEstancia.idHotel.imagenPortada}}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{estanciaPack.idEstancia.idHotel.nombre}}</h5>
              <ul class="card-text">
                <li>Habitación: {{estanciaPack.idEstancia.habitacion}}</li>
                <li>Número de noches: {{estanciaPack.idEstancia.noches}}</li>
                <li>Pensión: {{estanciaPack.idEstancia.tipoPension}}</li>
              </ul>
            </div>
          </a>
        </div>
      </div>
      {% else %}
      Este pack todavía no tiene estancias añadidas.

      {% endfor %}
    </div>
  </div>
</div>
</div>




  <style>
    .cuadrado {
      width: 100px;
      height: 100px;
    }
  </style>
  <script> function copiar(obj) { var i = document.getElementById('destino'); i.setAttribute('src', obj.getAttribute('src')); } </script>




{% endblock %}

{% block javascript %}


{% endblock %}

templates/paquetes/paquetesGrupo.html.twig
{% extends 'base.html.twig' %}

{% block title %}TripAddict | Paquetes{% endblock %}

{% block body %}
<div class="card mb-2 mt-4  text-primary">
  <div class="card-header ">
    <h2 class="text-center">{{grupo.titulo |upper}}</h2>
  </div>
  <div class="card-body">
    <div class="row mb-3 d-flex">

      {% for paquete in grupo.packs %}
      <div class='col-md-3 mb-5'>
        <div class="card">
          <img class="card-img-top" src="\images\ImagenesPortadas\{{paquete.imagenPortada}}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{paquete.nombre}}</h5>
            <p class="card-text text-left">
              {{ paquete.descripcion|length > 150 ? paquete.descripcion|slice(0, 150) ~ '...' : paquete.descripcion  }}
            </p>
            <p class='text-primary'><strong>{{paquete.precio}}€</strong></p>
            <a href="/paquetes/{{grupo.id}}/{{paquete.id}}" class="btn btn-info btn-block card-link">Ver Pack</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

</div>

{% endblock %}